namespace:
  create: true
  name: accessiq-dev

backend:
  replicaCount: 1
  image:
    repository: accessiq-api
    tag: latest
    pullPolicy: IfNotPresent
  config:
    corsAllowedOrigins: http://localhost:5173,http://127.0.0.1:5173,http://accessiq.local
  secrets:
    jwtSecret: dev-accessiq-change-me-minimum-32-bytes
  autoscaling:
    enabled: false
  pdb:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

frontend:
  replicaCount: 1
  image:
    repository: accessiq-frontend
    tag: latest
    pullPolicy: IfNotPresent
  apiBaseUrl: http://accessiq.local
  autoscaling:
    enabled: false
  pdb:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

database:
  internal:
    enabled: true
    auth:
      database: accessiq
      username: accessiq
      password: accessiq-dev-password
    persistence:
      size: 1Gi

ingress:
  enabled: true
  className: nginx
  host: accessiq.local

networkPolicies:
  enabled: false
