{{- if .Values.frontend.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "accessiq.frontendName" . }}
  namespace: {{ include "accessiq.namespace" . }}
  labels:
    {{- include "accessiq.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  minAvailable: {{ .Values.frontend.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "accessiq.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
{{- end }}
