{{- if and .Values.database.internal.enabled (not .Values.database.internal.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accessiq.postgresqlSecretName" . }}
  namespace: {{ include "accessiq.namespace" . }}
  labels:
    {{- include "accessiq.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  {{ .Values.database.internal.auth.passwordKey }}: {{ .Values.database.internal.auth.password | quote }}
{{- end }}

